### PR TITLE
added quick sort

### PR DESCRIPTION
**Pull request by jsroyal**
@pedrovgs Please review it.

### CODE REVIEW

**Comment by jsroyal** [comment]
Hey! @pedrovgs Please, can you check which test case I failed.
Could you help me understand Travis CI coz still fill scary (:

**Comment by jsroyal** [comment]
Hey! @pedrovgs I got something but could not understand. So can you do me favor.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.399 s
[INFO] Finished at: 2017-03-27T13:59:53+00:00
[INFO] Final Memory: 20M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.10:checkstyle (default-cli) on project algorithms: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 7 checkstyle errors. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command "mvn checkstyle:checkstyle" exited with 1.
Done. Your build exited with 1.

**Comment by pedrovgs** [comment]
Hi @jsroyal your problem is not related to any test, it's related to the project checkstyle configured.  [Here](https://github.com/pedrovgs/Algorithms/blob/master/checkstyle.xml) you can find the checkstyle configuration and instructions to configure it.

**Comment by pedrovgs** [comment]
You should also review the other ``SortingAlgorithm`` tests. Right now you are not covering your code with any test and every algorithm should be tested in this repository. Thank you so much for your time and effort 😃

**Comment by jsroyal** [comment]
@pedrovgs Hi!, I don't understand all checksum.
could you help me?
how to pass it ?

**Comment by pedrovgs** [comment]
@jsroyal you have to install [this](https://github.com/square/java-code-styles) checkstyle configuration into your Android Studio or IntelliJ and reformat your ``QuickSort.java`` file. Review also the tests implementation, we can't merge any algorithm if it's not tested.

**Comment by jsroyal** [comment]
Sorry to delay @pedrovgs . It has been such long time.
Actually, I do code in sublime3 text and some time NetBeans.
So in the environment what should I do?
Can you please help how can I pass this test case in this environment or I do need to move into IntelliJ IDE.Basically, I used Ubuntu 16.01, So yes, please suggest me.

**Comment by letientai299** [comment]
@jsroyal, make sure to run `mvn test` in your local pc and ensure that all test pass.

**Comment by jsroyal** [comment]
@letientai299 Thanks.
Actually, I never write any test case for code before.
I don't know how to run mvn test.
Do you know how to write it and run it?

**Comment by jsroyal** [comment]
@pedrovgs Please, now you can merge it and I added style and also existing test case from sorting algorithms.

**Comment by pedrovgs** [comment]
@jsroyal this is ready to merge. Thanks for your time and contribution to this project.

**Pull request merged**
